name: "Dep Jobs Examples"

on: [push]

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: jobs1
    steps:
    - name: stepA
      run: echo "World"
  jobs1:
    runs-on: ubuntu-latest
    steps:
    - name: stepB
      run: echo "Hello"